"""Validate mdpy GPU tile list and forces against brute-force O(N^2) reference.

Reference data generated by generate_bruteforce_reference.py.
Run that script first to create bruteforce_reference_1M9Z.npz.
"""

import os
import numpy as np
import pytest

DATA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'data')

PSF_PATH = os.path.join(DATA_DIR, '1M9Z.psf')
PDB_PATH = os.path.join(DATA_DIR, '1M9Z_minimized.pdb')
PRM_PATH = os.path.join(DATA_DIR, 'par_all36_prot.prm')
STR_PATH = os.path.join(DATA_DIR, 'toppar_water_ions.str')
REF_PATH = os.path.join(DATA_DIR, 'bruteforce_reference_1M9Z.npz')

BOX_SIZE = 108.0
CUTOFF = 12.0
SENTINEL = 0x7FFFFFFF
W = 32


def _load_reference():
    if not os.path.exists(REF_PATH):
        pytest.skip(
            f'Reference file not found: {REF_PATH}. '
            f'Run generate_bruteforce_reference.py first.'
        )
    return dict(np.load(REF_PATH, allow_pickle=True))


def _setup_mdpy_system():
    from mdpy.io.psf_parser import PSFParser
    from mdpy.io.pdb_parser import PDBParser
    from mdpy.io.charmm_toppar_parser import CharmmTopparParser
    from mdpy.io.charmm_toppar_parser import create_parameter_table
    from mdpy.force.bonded_force import BondedForce
    from mdpy.force.nonbonded_force import NonbondedForce
    from mdpy.force.expressions.lennard_jones import lennard_jones
    from mdpy.force.expressions.coulomb import coulomb
    from mdpy.system import System

    psf = PSFParser(PSF_PATH)
    pdb = PDBParser(PDB_PATH)
    toppar = CharmmTopparParser(PRM_PATH, STR_PATH)
    topology = psf.topology
    parameter_table = create_parameter_table(topology, toppar)
    pbc_matrix = np.eye(3, dtype=np.float64) * BOX_SIZE
    pbc_inv = np.linalg.inv(pbc_matrix)

    system = System(topology, pbc_matrix, cutoff=CUTOFF)
    system.add_force_term(BondedForce.charmm(topology, parameter_table))
    nb = NonbondedForce(lennard_jones + coulomb)
    nb.bind(topology, parameter_table, CUTOFF)
    system.add_force_term(nb)

    raw = pdb.positions.astype(np.float64)
    frac = raw @ pbc_inv
    frac -= np.floor(frac)
    wrapped = frac @ pbc_matrix
    system.particles.positions[:] = wrapped
    system.gpu.upload_positions(system.particles)
    system.gpu.refresh_wrapped_positions()
    positions_2d = (
        system.gpu.d_wrapped_positions_x,
        system.gpu.d_wrapped_positions_y,
        system.gpu.d_wrapped_positions_z,
    )
    system.tile_list.rebuild(
        positions_2d, topology, system.pbc_matrix, system.pbc_inv,
    )
    system._permute_all_arrays()
    system.tile_list.build_tiles(topology, system.pbc_matrix)
    for term in system.force_terms:
        if hasattr(term, 'bind_sorted'):
            term.bind_sorted(topology, system.tile_list, system.gpu)
    return system


def _extract_tile_pairs(system):
    import cupy as cp
    tl = system.tile_list
    block_atoms = tl.block_atoms
    tiles = tl.tiles
    interacting_atoms = tl.interacting_atoms
    exclusion_masks = tl.exclusion_masks
    scaling_masks = tl.scaling_masks

    sorted_to_pdb = cp.asnumpy(tl.d_sorted_to_pdb)

    pair_set = set()
    excluded_pair_set = set()
    scaled_pair_set = set()

    num_tiles = len(tiles)
    for tile_idx in range(num_tiles):
        block_x = tiles[tile_idx]
        exc_mask = exclusion_masks[tile_idx]
        scl_mask = scaling_masks[tile_idx]
        for slot_j in range(W):
            atom_j_sorted = interacting_atoms[tile_idx, slot_j]
            if atom_j_sorted == SENTINEL:
                continue
            atom_j = int(sorted_to_pdb[atom_j_sorted])
            for slot_i in range(W):
                atom_i_sorted = block_atoms[block_x, slot_i]
                if atom_i_sorted == SENTINEL:
                    continue
                atom_i = int(sorted_to_pdb[atom_i_sorted])
                if atom_i == atom_j:
                    continue
                a, b = min(atom_i, atom_j), max(atom_i, atom_j)
                pair_set.add((a, b))
                bit = 1 << slot_i
                if exc_mask[slot_j] & bit:
                    excluded_pair_set.add((a, b))
                if scl_mask[slot_j] & bit:
                    scaled_pair_set.add((a, b))

    return pair_set, excluded_pair_set, scaled_pair_set


@pytest.fixture(scope='module')
def ref():
    return _load_reference()


@pytest.fixture(scope='module')
def mdpy_system():
    return _setup_mdpy_system()


@pytest.mark.slow
class TestTileListValidation:

    def test_neighbor_pair_completeness(self, mdpy_system, ref):
        pair_set, _, _ = _extract_tile_pairs(mdpy_system)
        ref_i = ref['neighbor_pairs_i']
        ref_j = ref['neighbor_pairs_j']
        ref_flags = ref['pair_exclusion_flags']
        non_excluded = ref_flags != 1
        ref_pairs = set(zip(ref_i[non_excluded], ref_j[non_excluded]))
        missing = ref_pairs - pair_set
        assert len(missing) == 0, (
            f'Tile list is missing {len(missing)} non-excluded neighbor pairs '
            f'out of {len(ref_pairs)} total. '
            f'First 5 missing: {list(missing)[:5]}'
        )

    def test_exclusion_masks_correct(self, mdpy_system, ref):
        _, excluded_pair_set, scaled_pair_set = _extract_tile_pairs(mdpy_system)
        ref_i = ref['neighbor_pairs_i']
        ref_j = ref['neighbor_pairs_j']
        ref_flags = ref['pair_exclusion_flags']
        ref_excluded = set(zip(ref_i[ref_flags == 1], ref_j[ref_flags == 1]))
        ref_scaled = set(zip(ref_i[ref_flags == 2], ref_j[ref_flags == 2]))
        missing_excl = ref_excluded - excluded_pair_set
        assert len(missing_excl) == 0, (
            f'{len(missing_excl)} excluded pairs not marked in tile list masks'
        )
        missing_scl = ref_scaled - scaled_pair_set
        assert len(missing_scl) == 0, (
            f'{len(missing_scl)} scaled(1-4) pairs not marked in tile list masks'
        )

    def test_atom_mapping_consistency(self, mdpy_system):
        tl = mdpy_system.tile_list
        N = mdpy_system.topology.num_particles
        assert tl.d_sorted_to_pdb.shape[0] == N
        sorted_to_pdb = __import__('cupy').asnumpy(tl.d_sorted_to_pdb)
        pdb_ids = sorted(int(x) for x in sorted_to_pdb)
        assert pdb_ids == list(range(N))


@pytest.mark.slow
class TestBondedForces:

    def test_bonded_energy(self, mdpy_system, ref):
        mdpy_system.compute_forces()
        energies = mdpy_system.dump_energy()
        ref_energy = float(ref['bonded_energy'])
        mdpy_energy = energies.get('bonded', 0.0)
        denom = max(abs(ref_energy), abs(mdpy_energy))
        if denom < 1e-14:
            return
        rel_err = abs(mdpy_energy - ref_energy) / denom
        assert rel_err < 1e-4, (
            f'Bond energy: mdpy={mdpy_energy:.8f}, ref={ref_energy:.8f}, '
            f'rel_err={rel_err:.6e}'
        )

    def _get_pdb_forces(self, mdpy_system):
        import cupy as cp
        tl = mdpy_system.tile_list
        gpu = mdpy_system.gpu
        sorted_to_pdb = tl.d_sorted_to_pdb
        pdb_fx = gpu.permute_from_sorted(sorted_to_pdb, gpu.d_forces_x).get()
        pdb_fy = gpu.permute_from_sorted(sorted_to_pdb, gpu.d_forces_y).get()
        pdb_fz = gpu.permute_from_sorted(sorted_to_pdb, gpu.d_forces_z).get()
        return np.stack([pdb_fx, pdb_fy, pdb_fz], axis=1).astype(np.float64)

    def test_total_forces_correlation(self, mdpy_system, ref):
        mdpy_system.compute_forces()
        mdpy_forces = self._get_pdb_forces(mdpy_system)
        ref_forces = ref['total_forces']
        mask = np.any(np.abs(ref_forces) > 1e-8, axis=1)
        if not np.any(mask):
            return
        corr = np.corrcoef(mdpy_forces[mask].flatten(), ref_forces[mask].flatten())[0, 1]
        assert corr > 0.99, f'Total forces correlation: {corr:.6f}'


@pytest.mark.slow
class TestBondedEnergies:

    def _compute_and_get_energies(self, mdpy_system):
        mdpy_system.compute_forces()
        energies = mdpy_system.dump_energy()
        return energies

    def test_total_bonded_energy(self, mdpy_system, ref):
        energies = self._compute_and_get_energies(mdpy_system)
        ref_total = float(ref['bonded_energy'])
        mdpy_total = energies.get('bonded', 0.0)
        denom = max(abs(ref_total), abs(mdpy_total))
        if denom < 1e-14:
            return
        rel_err = abs(mdpy_total - ref_total) / denom
        assert rel_err < 1e-4, (
            f'Total bonded energy: mdpy={mdpy_total:.8f}, ref={ref_total:.8f}, '
            f'rel_err={rel_err:.6e}'
        )

    def test_total_energy(self, mdpy_system, ref):
        energies = self._compute_and_get_energies(mdpy_system)
        ref_total = float(ref['total_energy'])
        mdpy_total = sum(energies.values())
        denom = max(abs(ref_total), abs(mdpy_total))
        if denom < 1e-14:
            return
        rel_err = abs(mdpy_total - ref_total) / denom
        assert rel_err < 1e-3, (
            f'Total energy: mdpy={mdpy_total:.8f}, ref={ref_total:.8f}, '
            f'rel_err={rel_err:.6e}'
        )


@pytest.mark.slow
class TestNonbondedForces:

    def test_nonbonded_energy(self, mdpy_system, ref):
        mdpy_system.compute_forces()
        energies = mdpy_system.dump_energy()
        ref_energy = float(ref['nonbonded_energy'])
        mdpy_energy = energies.get('nonbonded', 0.0)
        denom = max(abs(ref_energy), abs(mdpy_energy))
        if denom < 1e-14:
            return
        rel_err = abs(mdpy_energy - ref_energy) / denom
        assert rel_err < 1e-3, (
            f'Nonbonded energy: mdpy={mdpy_energy:.8f}, ref={ref_energy:.8f}, '
            f'rel_err={rel_err:.6e}'
        )

    def _get_pdb_forces(self, mdpy_system):
        import cupy as cp
        tl = mdpy_system.tile_list
        gpu = mdpy_system.gpu
        sorted_to_pdb = tl.d_sorted_to_pdb
        pdb_fx = gpu.permute_from_sorted(sorted_to_pdb, gpu.d_forces_x).get()
        pdb_fy = gpu.permute_from_sorted(sorted_to_pdb, gpu.d_forces_y).get()
        pdb_fz = gpu.permute_from_sorted(sorted_to_pdb, gpu.d_forces_z).get()
        return np.stack([pdb_fx, pdb_fy, pdb_fz], axis=1).astype(np.float64)

    def test_nonbonded_force_direction(self, mdpy_system, ref):
        mdpy_system.compute_forces()
        mdpy_forces = self._get_pdb_forces(mdpy_system)
        ref_total = ref['total_forces']
        ref_bonded = ref['bonded_forces']
        ref_nonbonded = ref_total - ref_bonded
        mask = np.any(np.abs(ref_nonbonded) > 1e-6, axis=1)
        if not np.any(mask):
            return
        corr = np.corrcoef(mdpy_forces[mask].flatten(), ref_nonbonded[mask].flatten())[0, 1]
        assert corr > 0.99, f'Nonbonded force direction correlation: {corr:.6f}'

    def test_total_force_correlation(self, mdpy_system, ref):
        mdpy_system.compute_forces()
        mdpy_forces = self._get_pdb_forces(mdpy_system)
        ref_forces = ref['total_forces']
        mask = np.any(np.abs(ref_forces) > 1e-8, axis=1)
        if not np.any(mask):
            return
        corr = np.corrcoef(mdpy_forces[mask].flatten(), ref_forces[mask].flatten())[0, 1]
        assert corr > 0.99, f'Total force correlation: {corr:.6f}'

    def test_force_magnitude_correlation(self, mdpy_system, ref):
        mdpy_system.compute_forces()
        mdpy_forces = self._get_pdb_forces(mdpy_system)
        ref_forces = ref['total_forces']
        ref_norms = np.linalg.norm(ref_forces, axis=1)
        mdpy_norms = np.linalg.norm(mdpy_forces, axis=1)
        mask = ref_norms > 1e-8
        if not np.any(mask):
            return
        corr = np.corrcoef(ref_norms[mask], mdpy_norms[mask])[0, 1]
        assert corr > 0.99, f'Force magnitude correlation: {corr:.6f}'


@pytest.mark.slow
class TestMultiStepConsistency:

    def test_energy_changes_after_position_perturbation(self, mdpy_system):
        import cupy as cp
        mdpy_system.compute_forces()
        energies_1 = mdpy_system.dump_energy()
        e1 = energies_1.get('nonbonded', 0.0)

        gpu = mdpy_system.gpu
        cp.add(gpu.d_positions_x, np.float32(0.5), out=gpu.d_positions_x)

        mdpy_system.compute_forces()
        energies_2 = mdpy_system.dump_energy()
        e2 = energies_2.get('nonbonded', 0.0)

        denom = max(abs(e1), abs(e2))
        if denom < 1e-14:
            return
        rel_change = abs(e2 - e1) / denom
        assert rel_change > 1e-8, (
            f'Nonbonded energy did not change after perturbation: '
            f'e1={e1:.8f}, e2={e2:.8f}, rel_change={rel_change:.6e}. '
            f'Stale position data suspected.'
        )
