"""Validate mdpy GPU PME reciprocal force against O(N^2) Ewald reciprocal brute-force.

Reference data generated by generate_bruteforce_reference.py.
"""

import os

import numpy as np
import pytest

DATA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'data')

PSF_PATH = os.path.join(DATA_DIR, '1M9Z.psf')
PDB_PATH = os.path.join(DATA_DIR, '1M9Z_minimized.pdb')
PRM_PATH = os.path.join(DATA_DIR, 'par_all36_prot.prm')
STR_PATH = os.path.join(DATA_DIR, 'toppar_water_ions.str')
REF_PATH = os.path.join(DATA_DIR, 'bruteforce_reference_1M9Z.npz')

BOX_SIZE = 108.0
CUTOFF = 12.0


def _load_reference():
    if not os.path.exists(REF_PATH):
        pytest.skip(
            f'Reference file not found: {REF_PATH}. '
            f'Run generate_bruteforce_reference.py first.'
        )
    return dict(np.load(REF_PATH, allow_pickle=True))


def _setup_pme_system():
    from mdpy.io.psf_parser import PSFParser
    from mdpy.io.pdb_parser import PDBParser
    from mdpy.io.charmm_toppar_parser import CharmmTopparParser
    from mdpy.io.charmm_toppar_parser import create_parameter_table
    from mdpy.force.bonded_force import BondedForce
    from mdpy.force.nonbonded_force import NonbondedForce
    from mdpy.force.expressions.lennard_jones import lennard_jones
    from mdpy.force.expressions.screened_coulomb import screened_coulomb
    from mdpy.force.pme_reciprocal_force import PMEReciprocalForce
    from mdpy.system import System

    psf = PSFParser(PSF_PATH)
    pdb = PDBParser(PDB_PATH)
    toppar = CharmmTopparParser(PRM_PATH, STR_PATH)
    topology = psf.topology
    parameter_table = create_parameter_table(topology, toppar)
    pbc_matrix = np.eye(3, dtype=np.float64) * BOX_SIZE
    pbc_inv = np.linalg.inv(pbc_matrix)

    system = System(topology, pbc_matrix, cutoff=CUTOFF)

    system.add_force_term(BondedForce.charmm(topology, parameter_table))

    nb = NonbondedForce(lennard_jones + screened_coulomb)
    nb.bind(topology, parameter_table, CUTOFF)
    system.add_force_term(nb)

    pme = PMEReciprocalForce(CUTOFF)
    pme.bind(topology, parameter_table, pbc_matrix=pbc_matrix)
    system.add_force_term(pme)

    raw = pdb.positions.astype(np.float64)
    frac = raw @ pbc_inv
    frac -= np.floor(frac)
    wrapped = frac @ pbc_matrix
    system.upload_positions(wrapped.astype(np.float32))
    system.upload_velocities(
        np.zeros((topology.num_particles, 3), dtype=np.float32)
    )

    positions_soa = (
        system.gpu.d_positions_x,
        system.gpu.d_positions_y,
        system.gpu.d_positions_z,
    )
    system.block_list.rebuild(
        positions_soa, topology, system.pbc_matrix, system.pbc_inv
    )
    system._permute_all_arrays()
    system.block_list.build_block_pairs(topology, system.pbc_matrix)
    for term in system.force_terms:
        if hasattr(term, 'bind_sorted'):
            term.bind_sorted(topology, system.block_list, system.gpu)
    return system


def _get_pdb_forces(system):
    bl = system.block_list
    gpu = system.gpu
    sorted_to_pdb = bl.d_sorted_to_pdb
    pdb_fx = gpu.permute_from_sorted(sorted_to_pdb, gpu.d_forces_x).get()
    pdb_fy = gpu.permute_from_sorted(sorted_to_pdb, gpu.d_forces_y).get()
    pdb_fz = gpu.permute_from_sorted(sorted_to_pdb, gpu.d_forces_z).get()
    return np.stack([pdb_fx, pdb_fy, pdb_fz], axis=1).astype(np.float64)


@pytest.fixture(scope='module')
def ref():
    return _load_reference()


@pytest.fixture(scope='module')
def pme_system():
    return _setup_pme_system()


@pytest.mark.slow
class TestPMEBruteForce:

    @pytest.mark.xfail(
        reason='PME grid energy contribution near zero — pre-existing Bk bug'
    )
    def test_pme_energy(self, pme_system, ref):
        energies = pme_system.dump_energy()
        gpu_energy = energies['pme_reciprocal']
        ref_energy = float(ref['pme_recip_energy'])
        denom = max(abs(ref_energy), abs(gpu_energy))
        if denom < 1e-14:
            return
        rel_err = abs(gpu_energy - ref_energy) / denom
        assert rel_err < 0.05, (
            f'PME reciprocal energy: gpu={gpu_energy:.4f}, '
            f'ref={ref_energy:.4f}, rel_err={rel_err:.4e}'
        )

    @pytest.mark.xfail(
        reason='PME grid energy contribution near zero — pre-existing Bk bug'
    )
    def test_pme_energy_reasonable(self, pme_system):
        energies = pme_system.dump_energy()
        pme_energy = energies['pme_reciprocal']
        assert pme_energy < 0, (
            f'PME reciprocal energy should be negative, got {pme_energy:.4f}'
        )
        assert -2000 < pme_energy < -100, (
            f'PME reciprocal energy out of expected range: {pme_energy:.4f}'
        )

    def test_pme_forces_finite(self, pme_system):
        pme_system.compute_forces()
        forces = _get_pdb_forces(pme_system)
        assert not np.any(np.isnan(forces)), 'PME forces contain NaN'
        assert not np.any(np.isinf(forces)), 'PME forces contain Inf'
