package:
    name: mdpy
    version: 0.2.0

build:
    skip: True [py<35]

source:
    path: ./  

requirements:
    build:
        - python >=3.7
        - setuptools
    run:
        - python >=3.7
        - numpy >=1.20.0
        - scipy >=1.7.0
        - matplotlib >=3.5.0
        - pytest >=6.2.0
        - pytest-xdist >=2.3.0
        - mdanalysis
        
about:
    home: https://mdpy.net/
    license: GNU General Public License v3 (GPLv3)
    license_file: LICENSE